config/routes.rb
Blogtwitter::Application.routes.draw do
  match '/auth/:provider/callback' => 'authentications#create'
  resources :authentications
  resources :articles do
    resource :post
  end
  devise_for :users, :controllers => { :registrations => 'registrations', :sessions => 'sessions'}

  root :to => 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :name, :description
  has_many :posts
  belongs_to :user
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  attr_accessible :user_id, :provider, :uid, :name, :oauth_token, :oauth_token_secret
  belongs_to :user
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :post
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  # attr_accessible :title, :body

  has_many :authentications
  has_many :articles
  has_many :posts



  def apply_omniauth(omniauth)
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'], :oauth_token => omniauth.credentials[:token], :oauth_token_secret => omniauth.credentials[:secret], :name => omniauth.info[:nickname])
  end
  
  def initialize_fields
    self.status = "Active"
    self.expiration_date = 1.year.from_now
  end
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user!

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    @user = current_user
  end
  
  def new
    @article = Article.new
  end
  
  def show
    @article = Article.where(:id => params[:id]).first
  end

  def create
    @article = Article.new(params[:article])
    @article.user_id = current_user.id
    if @article.save
      if !current_user.authentications.blank?
        auth = current_user.authentications.first
        @client = Twitter::Client.new(
                                      :oauth_token => auth.oauth_token,
                                      :oauth_token_secret => auth.oauth_token_secret
                                      )
        @client.update("created article - #{@article.name}")
      end
      redirect_to articles_path
    else
      render :action => 'new'
    end
  end
  
  def edit
  end
  
  def update
  end

  def desroy
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :create

  
  def index
    @authentications = current_user.authentications if current_user
  end
  
  def create
#    auth =  request.env["omniauth.auth"]
#    auth = request.env["omniauth.auth"]
#    current_user.authentications.find_or_create_by_provider_and_uid(auth['provider'], auth['uid'])
#    current_user.authentications.update_all(:oauth_token => auth.credentials[:token], :oauth_token_secret => auth.credentials[:secret], :name => auth.info[:nickname])
#    flash[:notice] = "Authentication successful."
#    render :text => "success"
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.find_by_provider_and_uid(omniauth['provider'], omniauth['uid'])
    if authentication
      flash[:notice] = "Signed in successfully."
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      flash[:notice] = "Authentication successful."
      redirect_to authentications_url
    else
      user = User.new
      
      if user.save
        flash[:notice] = "Signed in successfully."
        sign_in_and_redirect(:user, user)
      else
        session[:omniauth] = omniauth.except('extra')
        redirect_to new_user_registration_url
      end
    end
    
  end
  
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
     @article = Article.where(:id => params[:article_id]).first
     @post = Post.new
  end

  def create
    puts @atricle = Article.where(:id => params[:article_id]).first
    @post = Post.new(params[:post])
    @post.article_id = @atricle.id
    @post.user_id = current_user.id
    if @post.save

      if !current_user.authentications.blank? 
        auth = current_user.authentications.first
        @client = Twitter::Client.new(
                                      :oauth_token => auth.oauth_token,
                                      :oauth_token_secret => auth.oauth_token_secret
                                      )
        @client.update("comment  on #{@atricle.name}")
      end
        redirect_to article_path(@atricle)
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
     # Building the resource with information that MAY BE available from omniauth!
     build_resource(:first_name => session[:omniauth] && session[:omniauth]['user_info'] && session[:omniauth]['user_info']['first_name'],
         :last_name => session[:omniauth] && session[:omniauth]['user_info'] && session[:omniauth]['user_info']['last_name'],
         :email => session[:omniauth_email] )
     render :new
  end

  def create
    build_resource

    if session[:omniauth] && @user.errors[:email][0] =~ /has already been taken/
      user = User.find_by_email(@user.email)
      # Link Accounts - if via social connect
      return redirect_to link_accounts_url(user.id)
    end

    # normal processing
    super
    session[:omniauth] = nil unless @user.new_record?
  end

  def build_resource(*args)
    super

    if session[:omniauth]
      @user.apply_omniauth(session[:omniauth])
      @user.valid?
    end
  end

  def after_update_path_for(scope)
    session[:referrer] ? session[:referrer] : root_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @articles = Article.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>

  <div><%= f.label :name %><br />
  <%= f.text_field :name %></div>

  <div><%= f.label :descriprtion %><br />
  <%= f.text_field :description %></div>

  <div><%= f.submit "Post" %></div>
<% end %>

app/views/articles/index.html.erb
<h1>Articles</h1>
<div class="span6">
  <ul>
    <% @articles.each do |article| %>
    <li>
      <%= link_to article.name, article_path(article) %>
    </li>
    <% end %>
  </ul>
  <div id="newarticle">
    <%= link_to "new Article", new_article_path, :remote => :true , :class => 'btn'%>
  </div>
</div>
<div class="span6">
  <% if !@user.authentications.blank? %>
    <div id="tweets"></div>
    <script>
      jQuery(function($) {
      $("#tweets").liveTwitter('<%= @user.authentications.first.name %>');
      })
  <% end %>
    </script>
</div>

app/views/articles/new.js.erb
$('#newarticle').replaceWith("<%= escape_javascript(render(:partial => 'form'))%>");

app/views/articles/show.html.erb
<h1><%= @article.name %></h1>
<h3><%= @article.description %></h3>

<div>
  <ul>
    <% @article.posts.each do |post| %>
    <li>
      <%= post.post %>
    </li>
    <% end %>
  </ul>
</div>
<div id="newpost">
  <%= link_to "New Post", new_article_post_path(@article) , :remote => :true,  :class => "btn" %>
</div>
<%= link_to "Back", articles_path, :class => 'btn' %>

app/views/authentications/index.html.erb
<% title "Authentications" %>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
  </tr>
  <% for authentication in @authentications %>
    <tr>
      <td><%= authentication.user_id %></td>
      <td><%= authentication.provider %></td>
      <td><%= authentication.uid %></td>
      <td><%= link_to "Destroy", authentication, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogtwitter</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% if user_signed_in? %>
    <% end %>
    <div class="container">
      <% if user_signed_in? %>
        <div class="pull-right">
	  Welcome <%= current_user.email %>
	  <%= link_to "signout", destroy_user_session_path, :method => :delete%>
	</div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, :as => :post, :url => article_post_path(@article, @post), :html => { :class => "new_post" } do |f| %>

  <div><%= f.label :post %><br />
  <%= f.text_field :post %></div>

  <div><%= f.submit "Post" %></div>
<% end %>

app/views/posts/new.js.erb
$('#newpost').replaceWith("<%= escape_javascript(render(:partial => 'form'))%>");

app/views/welcome/index.html.erb
<h1>Welcome</h1>